version: '3.9'
services:
  ubersnap:
    build: .
    container_name: ubersnap
    ports:
        - "8080:8080"
    environment:
    - APP_TIMEOUT=2
    - SERVER_PORT=:8080
    - RBMQ_URL=amqp://admin:admin@localhost:5672/ubersnap